version: 0.2
phases:
  install:
    commands:
      - export BASE_URI=$ACCOUNT.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME 
      - export ECR_URI=$BASE_URI:$IMAGE_NAME;
  pre_build:
    commands:
      - aws --region $REGION ecr get-login-password | docker login --username AWS --password-stdin $BASE_URI
  build:
    commands:
      - docker build . -t $IMAGE_NAME -t $ECR_URI
  post_build:
    commands: 
      - docker push $ECR_URI
